# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f98f9283209b05b671f321c99189bd7ede907ac4645e3956776503f2674f9d11d5085d43171a82a8bd6746fdaf5c63e1f13ba5947d0d29af31861307142fab8a

test:
  secret_key_base: f2066cf4018a157f98da733820d0f4d7a8b0ab88e35f2e3ccbb810044ab999a9e63c41c1fa7706c470124949536ad519cdb4f8afc7353d34fc52d8683c552981

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
